############################
## CHANGE THESE
############################

baseURL: 'https://dounoit.github.io/linktree'
title: '@chefboyrdave2.1'

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


