############################
## Author
############################

author:
  name: "chefboyrdave2.1"
  image: twitter.jpg
  #image: author.png
  greeting: "cbrd21 linkTree :evergreen_tree:"
  #icon: ":wave:"
  icon: ":victory_hand:"

#https://www.webfx.com/tools/emoji-cheat-sheet/

############################
## Links
############################

links:
  - github: https://github.com/dounoit/L1nkr
  - link: https://github.com/dounoit/L1nkr#readme
  - website: https://dounoit.github.io
  - x-twitter:  https://x.com/cbrd21dash1
  # - mastodon: 
  # - linkedin: 
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 3

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: true

###############################
## OpenGraph & Twitter Cards
###############################

title: "linkTree"
description: "@chefboyrdave2.1"
images:
  - twitter.jpg
  #- thumbnail.png
